# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Release Maven Package

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup maven
      uses: s4u/maven-settings-action@v4.0.0
      with:
        githubServer: true
        servers: |
          [{
              "id": "central",
              "username": "${{ secrets.MVN_CENTRAL_USER }}",
              "password": "${{ secrets.MVN_CENTRAL_PASSWORD }}"
          }]
    - name: Configure Git user
      run: |
        grep id /home/runner/.m2/settings.xml
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
    - name: Deploy plugin to Maven repo
      run: |
        mvn -B release:prepare release:perform --file pom.xml
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_SIGNING_KEY_PASSPHRASE }}
        MAVEN_GPG_KEY: ${{ secrets.MAVEN_SIGNGING_KEY }}
